apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment-jcf
  labels:
    app: notes-app-jcf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-app-jcf
  template:
    metadata:
      labels:
        app: notes-app-jcf
    spec:
      containers:
      - name: notes-app-jcf
        image: 471112967512.dkr.ecr.us-east-1.amazonaws.com/notes-app-jcf:latest
        resources:
          requests:
            cpu: "300m"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000